modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="burger"
version="0.1.2"
displayName="Burger Mod"
displayURL="https://noobiezt0.com"
logoFile="logo.png"
credits="MCreator"
authors="noobiezt0"
description="Adds burgers and their ingredients!"
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.burger]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.123,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.burger]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration